name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    -uses: actions/checkout@v4
    -name: Set up Python 3.10
     uses: actions/setup-python@v3
     wtih:
      python-version: "3.10"
    - name: Run python program
    run: |
      python assignments/exerciste-2/main.py